In [1]:
import numpy as np


In [2]:
#Input array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
#Output
y=np.array([[1],[1],[0]])


In [3]:
print(X)

[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]


In [4]:
print(y)

[[1]
 [1]
 [0]]


In [6]:
#Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

In [7]:
#Derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)


In [54]:
#Variable initialization
epoch=1000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer


In [55]:
print(inputlayer_neurons)

4


In [56]:
#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))


In [57]:
print(wh)

[[0.90373126 0.94846453 0.20150139]
 [0.28671404 0.03030519 0.91134492]
 [0.55250171 0.83291554 0.7474625 ]
 [0.54471663 0.67437728 0.54365409]]


In [58]:
print(bh)

[[0.68514843 0.24938644 0.32645177]]


In [59]:
print(wout)

[[0.5954193 ]
 [0.63261599]
 [0.0569671 ]]


In [60]:
print(bout)

[[0.73834215]]


In [61]:
for i in range(epoch):

#Forward Propogation
    print("\n\n::::::::::FORWARD PROPAGATION:::::::::\n\n")
    hidden_layer_input1=np.dot(X,wh)
    print("H = X . Wh\n")
    print(hidden_layer_input1)
    hidden_layer_input=hidden_layer_input1 + bh
    print("\nH = X . Wh + bias_h")
    print(hidden_layer_input)
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    print("\nH_result: After applying activation function")
    print(hiddenlayer_activations)
    output_layer_input1=np.dot(hiddenlayer_activations,wout)
    print("\nOutput = H_result . Wout")
    print(output_layer_input1)
    output_layer_input= output_layer_input1+ bout
    print("\nOutput = H_result . Wout + bias_out")
    print(output_layer_input)
    output = sigmoid(output_layer_input)
    print("\nCalculated result: After applying activation function\n")
    print(output)

#Backpropagation
    print("\n\n::::::::::BACK PROPAGATION::::::::::::::\n\n")
    E = y-output
    print("Error=target-calculated")
    print(E)
    slope_output_layer = derivatives_sigmoid(output)
    print("Derivative of sigmoid (output)")
    print(slope_output_layer)
    d_output = E * slope_output_layer
    print("Delta output sum")
    print(d_output)
    
    wout += hiddenlayer_activations.T.dot(d_output) *lr
    print("Updated weight h-->o")
    print(wout)
    #wout += (d_output/hiddenlayer_activations.T) *lr
    
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    print("Updated output bias")
    print(bout)
    
    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
    
    Error_at_hidden_layer = d_output.dot(wout.T)
    
    
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    print("Delta hidden sum")
    print(d_hiddenlayer)
    
    
    wh += X.T.dot(d_hiddenlayer) *lr
    print("Updated weight i-->h")
    print(wh)
    
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr
    print("Updated bias i-->h")
    print(bh)
    
print("\nFinal result: After completing all iterations\n")
print(output)




::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[1.45623297 1.78138007 0.94896389]
 [2.0009496  2.45575735 1.49261798]
 [0.83143066 0.70468247 1.45499901]]

H = X . Wh + bias_h
[[2.1413814  2.03076652 1.27541566]
 [2.68609802 2.7051438  1.81906975]
 [1.51657909 0.95406891 1.78145078]]

H_result: After applying activation function
[[0.89486065 0.88398971 0.78166841]
 [0.93620132 0.93732949 0.86045447]
 [0.82003418 0.72193273 0.85587592]]

Output = H_result . Wout
[[1.13657272]
 [1.19941956]
 [0.99372715]]

Output = H_result . Wout + bias_out
[[1.87491487]
 [1.93776171]
 [1.7320693 ]]

Calculated result: After applying activation function

[[0.86702595]
 [0.87410604]
 [0.84967691]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.13297405]
 [ 0.12589396]
 [-0.84967691]]
Derivative of sigmoid (output)
[[0.11529196]
 [0.11004467]
 [0.12772606]]
Delta output sum
[[ 0.01533084]
 [ 0.01385396]
 [-0.10852588]]
Updated weight h-->o
[[0.58918872]
 [0.62743496]
 [

 [0.80826012 0.69702773 0.85654664]]

Output = H_result . Wout
[[0.71259668]
 [0.74446601]
 [0.57268412]]

Output = H_result . Wout + bias_out
[[1.22448348]
 [1.25635281]
 [1.08457092]]

Calculated result: After applying activation function

[[0.7728516 ]
 [0.77839763]
 [0.74735801]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.2271484 ]
 [ 0.22160237]
 [-0.74735801]]
Derivative of sigmoid (output)
[[0.17555201]
 [0.17249476]
 [0.18881401]]
Delta output sum
[[ 0.03987636]
 [ 0.03822525]
 [-0.14111167]]
Updated weight h-->o
[[ 0.42205059]
 [ 0.49950928]
 [-0.14809673]]
Updated output bias
[[0.50558579]]
Delta hidden sum
[[ 0.00159732  0.00207835 -0.00100892]
 [ 0.00099556  0.00118548 -0.00067971]
 [-0.00922977 -0.01488536  0.00256785]]
Updated weight i-->h
[[ 0.9098451   0.95573292  0.19987785]
 [ 0.25716162 -0.01461086  0.9140968 ]
 [ 0.55861555  0.84018393  0.74583897]
 [ 0.51746274  0.63203531  0.54575544]]
Updated bias i-->h
[[0.66170985 0.21173878 0.327


Output = H_result . Wout
[[0.54393675]
 [0.56173413]
 [0.39457567]]

Output = H_result . Wout + bias_out
[[0.94239579]
 [0.96019317]
 [0.79303472]]

Calculated result: After applying activation function

[[0.71958334]
 [0.72316048]
 [0.68848257]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.28041666]
 [ 0.27683952]
 [-0.68848257]]
Derivative of sigmoid (output)
[[0.20178316]
 [0.2001994 ]
 [0.21447432]]
Delta output sum
[[ 0.05658336]
 [ 0.05542311]
 [-0.14766183]]
Updated weight h-->o
[[ 0.35754335]
 [ 0.47265065]
 [-0.25146985]]
Updated output bias
[[0.39489351]]
Delta hidden sum
[[ 0.00192048  0.00280702 -0.00244674]
 [ 0.00124198  0.00168207 -0.00168067]
 [-0.0084427  -0.01525134  0.00451245]]
Updated weight i-->h
[[ 0.91658015  0.96478054  0.19302769]
 [ 0.23696696 -0.04914502  0.92254232]
 [ 0.56535059  0.84923155  0.73898881]
 [ 0.49988863  0.60084774  0.55142223]]
Updated bias i-->h
[[0.64825023 0.18625225 0.32917548]]


::::::::::FORWARD PROPAGATI

Error=target-calculated
[[ 0.30338365]
 [ 0.30111747]
 [-0.65868059]]
Derivative of sigmoid (output)
[[0.21134201]
 [0.21044574]
 [0.22482047]]
Delta output sum
[[ 0.06411771]
 [ 0.06336889]
 [-0.14808488]]
Updated weight h-->o
[[ 0.34082266]
 [ 0.49970115]
 [-0.31859007]]
Updated output bias
[[0.33104106]]
Delta hidden sum
[[ 0.00206815  0.00336859 -0.00356056]
 [ 0.00136891  0.0020968  -0.00246478]
 [-0.00830782 -0.0167055   0.00565328]]
Updated weight i-->h
[[ 0.92454707  0.97681339  0.18059188]
 [ 0.21700986 -0.08734274  0.93491541]
 [ 0.57331752  0.86126439  0.72655299]
 [ 0.483085    0.56721789  0.55871711]]
Updated bias i-->h
[[0.63626006 0.16008737 0.32911276]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[1.4978646  1.83807778 0.90714487]
 [1.9809496  2.40529567 1.46586199]
 [0.70009486 0.47987514 1.49363253]]

H = X . Wh + bias_h
[[2.13412466 1.99816515 1.23625764]
 [2.61720966 2.56538303 1.79497475]
 [1.33635492 0.63996251 1.82274529]]

H_result: After applying ac

 [-0.64285166]]
Derivative of sigmoid (output)
[[0.21374822]
 [0.21325034]
 [0.2295934 ]]
Delta output sum
[[ 0.06617666]
 [ 0.06574465]
 [-0.1475945 ]]
Updated weight h-->o
[[ 0.34755755]
 [ 0.55934308]
 [-0.37413302]]
Updated output bias
[[0.28567757]]
Delta hidden sum
[[ 0.00216724  0.00389254 -0.00440288]
 [ 0.00146438  0.0025214  -0.00306392]
 [-0.00870645 -0.01927391  0.00650905]]
Updated weight i-->h
[[ 0.93375629  0.99230903  0.16290246]
 [ 0.19494907 -0.13407549  0.9508079 ]
 [ 0.58252673  0.87676004  0.70886357]
 [ 0.46471608  0.52650713  0.56736125]]
Updated bias i-->h
[[0.62340848 0.12885027 0.32731583]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[1.51628302 1.86906906 0.87176603]
 [1.9809991  2.39557619 1.43912728]
 [0.65966515 0.39243165 1.51816915]]

H = X . Wh + bias_h
[[2.1396915  1.99791933 1.19908186]
 [2.60440759 2.52442646 1.76644311]
 [1.28307363 0.52128191 1.84548497]]

H_result: After applying activation function
[[0.89470155 0.88057845 0.76836141]



Error=target-calculated
[[ 0.30918049]
 [ 0.30880045]
 [-0.63179085]]
Derivative of sigmoid (output)
[[0.21358792]
 [0.21344273]
 [0.23263117]]
Delta output sum
[[ 0.06603722]
 [ 0.06591121]
 [-0.14697425]]
Updated weight h-->o
[[ 0.36170541]
 [ 0.62860996]
 [-0.42352685]]
Updated output bias
[[0.2492546]]
Delta hidden sum
[[ 0.00224157  0.00436631 -0.00508393]
 [ 0.00154477  0.00294716 -0.00355864]
 [-0.00928889 -0.02219532  0.00721991]]
Updated weight i-->h
[[ 0.9426681   1.00881512  0.14350792]
 [ 0.1733509  -0.1839026   0.96732241]
 [ 0.59143855  0.89326613  0.68946903]
 [ 0.4467333   0.48325338  0.57590354]]
Updated bias i-->h
[[0.61072213 0.09552924 0.3244358 ]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[1.53410665 1.90208125 0.83297695]
 [1.98083994 2.38533463 1.40888049]
 [0.6200842  0.29935078 1.54322595]]

H = X . Wh + bias_h
[[2.14482878 1.9976105  1.15741275]
 [2.59156207 2.48086388 1.73331629]
 [1.23080633 0.39488002 1.86766175]]

H_result: After applying ac

[[0.59320102 0.04651728 0.31920323]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[1.55738826 1.94972223 0.77646016]
 [1.97974915 2.36992158 1.36371666]
 [0.56654987 0.16346429 1.57760474]]

H = X . Wh + bias_h
[[2.15058929 1.9962395  1.09566339]
 [2.57295017 2.41643885 1.68291989]
 [1.1597509  0.20998156 1.89680797]]

H_result: After applying activation function
[[0.89572383 0.88040168 0.74944667]
 [0.92910028 0.91807229 0.84329079]
 [0.76128745 0.55230335 0.86952982]]

Output = H_result . Wout
[[0.61869215]
 [0.61302163]
 [0.26900128]]

Output = H_result . Wout + bias_out
[[0.82196857]
 [0.81629805]
 [0.4722777 ]]

Calculated result: After applying activation function

[[0.69465405]
 [0.69344995]
 [0.61592272]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.30534595]
 [ 0.30655005]
 [-0.61592272]]
Derivative of sigmoid (output)
[[0.2121098 ]
 [0.21257712]
 [0.23656192]]
Delta output sum
[[ 0.06476687]
 [ 0.06516552]
 [-0.14570386]]
Updated weight

 [0.60397613]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.30178313]
 [ 0.30428433]
 [-0.60397613]]
Derivative of sigmoid (output)
[[0.21071007]
 [0.21169538]
 [0.23918897]]
Delta output sum
[[ 0.06358874]
 [ 0.06441558]
 [-0.14446442]]
Updated weight h-->o
[[ 0.39899029]
 [ 0.80580758]
 [-0.53760612]]
Updated output bias
[[0.17105213]]
Delta hidden sum
[[ 0.00236395  0.0054006  -0.00656273]
 [ 0.00171279  0.00405873 -0.00469516]
 [-0.01073998 -0.02906001  0.00868734]]
Updated weight i-->h
[[ 0.96235858  1.05067947  0.0937819 ]
 [ 0.12328232 -0.31222061  1.00716826]
 [ 0.61112903  0.93513048  0.63974301]
 [ 0.40481548  0.37235756  0.5951509 ]]
Updated bias i-->h
[[0.58034403 0.00907558 0.31455563]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[1.57348761 1.98580994 0.73352491]
 [1.97830309 2.3581675  1.32867581]
 [0.5280978  0.06013695 1.60231916]]

H = X . Wh + bias_h
[[2.15383164 1.99488553 1.04808055]
 [2.55864712 2.36724308 1.64323144]
 [1.1

H = X . Wh

[[ 1.59756814  2.04488322  0.66322891]
 [ 1.97503768  2.34026879  1.27005334]
 [ 0.46829218 -0.10677073  1.64041889]]

H = X . Wh + bias_h
[[ 2.15749276  1.99355976  0.96906272]
 [ 2.53496229  2.28894533  1.57588716]
 [ 1.02821679 -0.15809419  1.94625271]]

H_result: After applying activation function
[[0.89636687 0.88011923 0.72493264]
 [0.92655675 0.90795735 0.82862125]
 [0.73657004 0.46055857 0.87503746]]

Output = H_result . Wout
[[0.75332446]
 [0.72839786]
 [0.20346468]]

Output = H_result . Wout + bias_out
[[0.87509634]
 [0.85016974]
 [0.32523656]]

Calculated result: After applying activation function

[[0.70580503]
 [0.70060275]
 [0.58059991]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.29419497]
 [ 0.29939725]
 [-0.58059991]]
Derivative of sigmoid (output)
[[0.20764429]
 [0.20975854]
 [0.24350365]]
Delta output sum
[[ 0.0610879 ]
 [ 0.06280113]
 [-0.1413782 ]]
Updated weight h-->o
[[ 0.42434075]
 [ 0.93441493]
 [-0.61607523]]
Updated o


[[0.71241536]
 [0.7049034 ]
 [0.5617454 ]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.28758464]
 [ 0.2950966 ]
 [-0.5617454 ]]
Derivative of sigmoid (output)
[[0.20487972]
 [0.2080146 ]
 [0.24618751]]
Delta output sum
[[ 0.05892026]
 [ 0.0613844 ]
 [-0.1382947 ]]
Updated weight h-->o
[[ 0.44253962]
 [ 1.02970183]
 [-0.67252285]]
Updated output bias
[[0.08448515]]
Delta hidden sum
[[ 0.00241883  0.00639688 -0.00811819]
 [ 0.00187778  0.00552873 -0.00607115]
 [-0.01220441 -0.03466321  0.01001864]]
Updated weight i-->h
[[ 0.98334621  1.10421392  0.03008596]
 [ 0.06577742 -0.47313318  1.0541258 ]
 [ 0.63211666  0.98866493  0.57604707]
 [ 0.35630068  0.2353573   0.6152169 ]]
Updated bias i-->h
[[ 0.54382676 -0.09830254  0.29781723]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[ 1.61546288  2.09287885  0.60613303]
 [ 1.97176356  2.32823614  1.22134994]
 [ 0.4220781  -0.23777588  1.6693427 ]]

H = X . Wh + bias_h
[[ 2.15928964  1.99457631  0.9039502

 [-0.52907856]]
Derivative of sigmoid (output)
[[0.19940139]
 [0.20455291]
 [0.24915444]]
Delta output sum
[[ 0.05484708]
 [ 0.05866921]
 [-0.13182227]]
Updated weight h-->o
[[ 0.472091  ]
 [ 1.18522799]
 [-0.76243789]]
Updated output bias
[[0.0298848]]
Delta hidden sum
[[ 0.00239949  0.00681616 -0.00893543]
 [ 0.00196498  0.00648879 -0.00697347]
 [-0.01292477 -0.03584564  0.0105974 ]]
Updated weight i-->h
[[ 0.99635629  1.14218867 -0.0151845 ]
 [ 0.02800089 -0.57947887  1.08513583]
 [ 0.64512673  1.02663968  0.53077661]
 [ 0.32429618  0.1470917   0.62662083]]
Updated bias i-->h
[[ 0.51906031 -0.16667347  0.28355679]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[ 1.64148302  2.16882835  0.51559211]
 [ 1.96577921  2.31592005  1.14221294]
 [ 0.35229708 -0.43238717  1.71175666]]

H = X . Wh + bias_h
[[ 2.16054333  2.00215488  0.7991489 ]
 [ 2.48483952  2.14924658  1.42576973]
 [ 0.87135739 -0.59906064  1.99531345]]

H_result: After applying activation function
[[0.89664991 0.8

 [0.02068686]]

Calculated result: After applying activation function

[[0.73500565]
 [0.71997336]
 [0.50517153]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.26499435]
 [ 0.28002664]
 [-0.50517153]]
Derivative of sigmoid (output)
[[0.19477235]
 [0.20161172]
 [0.24997326]]
Delta output sum
[[ 0.05161357]
 [ 0.05645665]
 [-0.12627937]]
Updated weight h-->o
[[ 0.49338355]
 [ 1.29508827]
 [-0.82503615]]
Updated output bias
[[-0.00666411]]
Delta hidden sum
[[ 0.00235983  0.00695274 -0.00935802]
 [ 0.00201359  0.00708217 -0.00757448]
 [-0.01328329 -0.03545765  0.01084375]]
Updated weight i-->h
[[ 1.00509982  1.16959851 -0.04809941]
 [ 0.00175627 -0.65091483  1.10660934]
 [ 0.65387026  1.05404951  0.4978617 ]
 [ 0.30203408  0.08926782  0.63351409]]
Updated bias i-->h
[[ 0.50155921 -0.2106996   0.2721154 ]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[ 1.65897008  2.22364802  0.44976229]
 [ 1.96100416  2.31291583  1.08327638]
 [ 0.30379035 -0.56164701 

 [ 0.27352036  0.0210501   0.64096242]]
Updated bias i-->h
[[ 0.47884789 -0.26152249  0.2556825 ]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[ 1.68077049  2.29550731  0.36224385]
 [ 1.95429085  2.31655742  1.00320627]
 [ 0.2416651  -0.71661726  1.77489808]]

H = X . Wh + bias_h
[[ 2.15961838  2.03398483  0.61792634]
 [ 2.43313874  2.05503493  1.25888876]
 [ 0.72051298 -0.97813975  2.03058058]]

H_result: After applying activation function
[[0.89656416 0.88431935 0.64974678]
 [0.91931964 0.88645538 0.77883476]
 [0.67271997 0.27326105 0.88397064]]

Output = H_result . Wout
[[ 1.14920621]
 [ 1.04730314]
 [-0.05685005]]

Output = H_result . Wout + bias_out
[[ 1.097494  ]
 [ 0.99559094]
 [-0.10856225]]

Calculated result: After applying activation function

[[0.74979026]
 [0.73019082]
 [0.47288606]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.25020974]
 [ 0.26980918]
 [-0.47288606]]
Derivative of sigmoid (output)
[[0.18760482]
 [0.19701219]
 [0.24

Updated weight i-->h
[[ 1.02547312  1.23793544 -0.13223679]
 [-0.06180859 -0.80968007  1.15808247]
 [ 0.67424357  1.12238645  0.41372433]
 [ 0.24813042 -0.03359088  0.64620643]]
Updated bias i-->h
[[ 0.45836766 -0.3011279   0.23945115]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[ 1.69971669  2.36032189  0.28148754]
 [ 1.94784711  2.32673101  0.92769397]
 [ 0.18632183 -0.84327094  1.8042889 ]]

H = X . Wh + bias_h
[[ 2.15808435  2.05919399  0.52093869]
 [ 2.40621477  2.02560311  1.16714512]
 [ 0.64468949 -1.14439884  2.04374005]]

H_result: After applying activation function
[[0.89642182 0.88687333 0.62736724]
 [0.91729998 0.88345914 0.76262859]
 [0.65581276 0.24151364 0.88531356]]

Output = H_result . Wout
[[ 1.26128326]
 [ 1.13533227]
 [-0.12858155]]

Output = H_result . Wout + bias_out
[[ 1.17102146]
 [ 1.04507047]
 [-0.21884335]]

Calculated result: After applying activation function

[[0.7633296 ]
 [0.73982717]
 [0.44550648]]


::::::::::BACK PROPAGATION::::::::::::::

[[ 0.44052282 -0.33112334  0.22432697]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[ 1.71577016  2.41631942  0.20984868]
 [ 1.94200113  2.3402298   0.85948863]
 [ 0.13855079 -0.94376389  1.82841766]]

H = X . Wh + bias_h
[[ 2.15629298  2.08519608  0.43417565]
 [ 2.38252394  2.00910646  1.0838156 ]
 [ 0.57907361 -1.27488723  2.05274463]]

H_result: After applying activation function
[[0.89625537 0.88945597 0.60687033]
 [0.91548492 0.88174989 0.74721537]
 [0.64085422 0.21842179 0.88622465]]

Output = H_result . Wout
[[ 1.36146443]
 [ 1.21396934]
 [-0.19051043]]

Output = H_result . Wout + bias_out
[[ 1.23899579]
 [ 1.09150069]
 [-0.31297908]]

Calculated result: After applying activation function

[[0.77538917]
 [0.74866421]
 [0.42238775]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.22461083]
 [ 0.25133579]
 [-0.42238775]]
Derivative of sigmoid (output)
[[0.17416081]
 [0.18816611]
 [0.24397634]]
Delta output sum
[[ 0.0391184 ]
 [ 0.04729288]
 [-

 [-0.29572769]]

Output = H_result . Wout + bias_out
[[ 1.3630606 ]
 [ 1.17815677]
 [-0.4713402 ]]

Calculated result: After applying activation function

[[0.79625668]
 [0.76461623]
 [0.38429909]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.20374332]
 [ 0.23538377]
 [-0.38429909]]
Derivative of sigmoid (output)
[[0.16223198]
 [0.17997825]
 [0.2366133 ]]
Delta output sum
[[ 0.03305368]
 [ 0.04236396]
 [-0.09093027]]
Updated weight h-->o
[[ 0.61307992]
 [ 1.84037677]
 [-1.14630219]]
Updated output bias
[[-0.17716377]]
Delta hidden sum
[[ 0.00189005  0.00574439 -0.00928911]
 [ 0.0020794   0.00820274 -0.0098387 ]
 [-0.01320506 -0.0254045   0.01042378]]
Updated weight i-->h
[[ 1.04736092  1.31468825 -0.23306546]
 [-0.1332844  -0.96076441  1.21493974]
 [ 0.69613137  1.19913926  0.31289565]
 [ 0.18773116 -0.14114563  0.6531953 ]]
Updated bias i-->h
[[ 0.40877965 -0.37545944  0.19547974]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[ 1.74349229  2.513

Delta hidden sum
[[ 0.00176228  0.00526246 -0.00886362]
 [ 0.00205227  0.00801671 -0.01003972]
 [-0.01283021 -0.02298659  0.01009022]]
Updated weight i-->h
[[ 1.0555289   1.34326506 -0.27302399]
 [-0.16061932 -1.01142978  1.23647174]
 [ 0.70429935  1.22771606  0.27293712]
 [ 0.16473543 -0.17477032  0.65382483]]
Updated bias i-->h
[[ 0.38961271 -0.39754799  0.17705322]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[ 1.75982825e+00  2.57098112e+00 -8.68713939e-05]
 [ 1.92456368e+00  2.39621081e+00  6.53737955e-01]
 [ 4.11610809e-03 -1.18620009e+00  1.89029657e+00]]

H = X . Wh + bias_h
[[ 2.14944096  2.17343313  0.17696635]
 [ 2.31417639  1.99866281  0.83079118]
 [ 0.39372882 -1.58374808  2.06734979]]

H_result: After applying activation function
[[0.89561653 0.8978383  0.54412649]
 [0.91004434 0.88065661 0.69652219]
 [0.59718001 0.17026532 0.88768901]]

Output = H_result . Wout
[[ 1.65642591]
 [ 1.44765122]
 [-0.36327648]]

Output = H_result . Wout + bias_out
[[ 1.44752315]
 

Output = H_result . Wout
[[ 1.80306312]
 [ 1.56618711]
 [-0.445582  ]]

Output = H_result . Wout + bias_out
[[ 1.55437295]
 [ 1.31749694]
 [-0.69427217]]

Calculated result: After applying activation function

[[0.82554442]
 [0.78876496]
 [0.33308338]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.17445558]
 [ 0.21123504]
 [-0.33308338]]
Derivative of sigmoid (output)
[[0.14402083]
 [0.1666148 ]
 [0.22213884]]
Delta output sum
[[ 0.02512524]
 [ 0.03519488]
 [-0.07399076]]
Updated weight h-->o
[[ 0.67384153]
 [ 2.07080122]
 [-1.29846788]]
Updated output bias
[[-0.25005724]]
Delta hidden sum
[[ 0.00158776  0.00459583 -0.00815136]
 [ 0.00199509  0.0076073  -0.01012821]
 [-0.01217976 -0.01992704  0.00956232]]
Updated weight i-->h
[[ 1.06624709  1.38018956 -0.32698657]
 [-0.1968824  -1.07341354  1.26495619]
 [ 0.71501754  1.26464057  0.21897454]
 [ 0.1343432  -0.2140849   0.65300902]]
Updated bias i-->h
[[ 0.36406782 -0.42260726  0.15157509]]


::::::::::FORWARD 

[[-0.2766207]]
Delta hidden sum
[[ 0.00147274  0.0041606  -0.00761571]
 [ 0.0019448   0.00725807 -0.01006762]
 [-0.01166993 -0.01803936  0.00917143]]
Updated weight i-->h
[[ 1.07323952  1.40377402 -0.36293855]
 [-0.22071282 -1.11125444  1.2836728 ]
 [ 0.72200997  1.28822503  0.18302257]
 [ 0.11445143 -0.23707134  0.65151722]]
Updated bias i-->h
[[ 0.34722983 -0.4368637   0.13433972]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[ 1.79524949  2.69199904 -0.17991598]
 [ 1.90970092  2.45492771  0.47160124]
 [-0.10626138 -1.34832578  1.93519002]]

H = X . Wh + bias_h
[[ 2.14247932  2.25513534 -0.04557626]
 [ 2.25693075  2.01806401  0.60594096]
 [ 0.24096845 -1.78518948  2.06952974]]

H_result: After applying activation function
[[0.8949639  0.90509258 0.48860791]
 [0.90524669 0.88268067 0.64701432]
 [0.55995229 0.14366352 0.88790617]]

Output = H_result . Wout
[[ 1.9093577 ]
 [ 1.65349562]
 [-0.50440836]]

Output = H_result . Wout + bias_out
[[ 1.63273699]
 [ 1.37687491]
 [-0.78

Updated weight i-->h
[[ 1.08247295  1.43415898 -0.41105004]
 [-0.25229729 -1.15830097  1.30854038]
 [ 0.73124339  1.31860999  0.13491107]
 [ 0.08819721 -0.26456229  0.64849227]]
Updated bias i-->h
[[ 0.32487879 -0.45352527  0.11109581]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[ 1.81371634  2.75276896 -0.27613897]
 [ 1.90191355  2.48820667  0.3723533 ]
 [-0.16410008 -1.42286326  1.95703266]]

H = X . Wh + bias_h
[[ 2.13859513  2.2992437  -0.16504316]
 [ 2.22679233  2.03468141  0.48344911]
 [ 0.16077871 -1.87638852  2.06812847]]

H_result: After applying activation function
[[0.89459822 0.90881438 0.45883262]
 [0.9026298  0.88439058 0.618562  ]
 [0.54010831 0.13280425 0.88776662]]

Output = H_result . Wout
[[ 2.04485024]
 [ 1.76674241]
 [-0.57883904]]

Output = H_result . Wout + bias_out
[[ 1.73349404]
 [ 1.4553862 ]
 [-0.89019525]]

Calculated result: After applying activation function

[[0.8498588 ]
 [0.81082599]
 [0.29106954]]


::::::::::BACK PROPAGATION::::::::::::::

Updated weight i-->h
[[ 1.08807091  1.4521116  -0.44044115]
 [-0.27146715 -1.18530457  1.32369574]
 [ 0.73684136  1.33656261  0.10551997]
 [ 0.07232866 -0.27979765  0.64614105]]
Updated bias i-->h
[[ 0.3113069  -0.46257625  0.09686006]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[ 1.82491227  2.7886742  -0.33492118]
 [ 1.89724094  2.50887655  0.31121986]
 [-0.19913848 -1.46510222  1.96983679]]

H = X . Wh + bias_h
[[ 2.13621917  2.32609796 -0.23806112]
 [ 2.20854783  2.04630031  0.40807993]
 [ 0.11216841 -1.92767847  2.06669686]]

H_result: After applying activation function
[[0.89437397 0.91101552 0.44076421]
 [0.90101449 0.88557325 0.60062739]
 [0.52801274 0.12700776 0.8876239 ]]

Output = H_result . Wout
[[ 2.12775319]
 [ 1.83721055]
 [-0.62425908]]

Output = H_result . Wout + bias_out
[[ 1.79553371]
 [ 1.50499107]
 [-0.95647856]]

Calculated result: After applying activation function

[[0.85760439]
 [0.8183177 ]
 [0.2775838 ]]


::::::::::BACK PROPAGATION::::::::::::::

H_result: After applying activation function
[[0.89399311 0.91466531 0.41009518]
 [0.89820762 0.88778124 0.56900451]
 [0.50725957 0.11822276 0.88731674]]

Output = H_result . Wout
[[ 2.27069728]
 [ 1.96093915]
 [-0.7026752 ]]

Output = H_result . Wout + bias_out
[[ 1.90305896]
 [ 1.59330083]
 [-1.07031352]]

Calculated result: After applying activation function

[[0.87023735]
 [0.83108   ]
 [0.25534347]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.12976265]
 [ 0.16892   ]
 [-0.25534347]]
Derivative of sigmoid (output)
[[0.11292431]
 [0.14038603]
 [0.19014318]]
Delta output sum
[[ 0.01465336]
 [ 0.02371401]
 [-0.04855182]]
Updated weight h-->o
[[ 0.78222054]
 [ 2.42162037]
 [-1.56315282]]
Updated output bias
[[-0.36865677]]
Delta hidden sum
[[ 0.00108626  0.00276969 -0.00554122]
 [ 0.001696    0.00572114 -0.00909065]
 [-0.00949256 -0.01225664  0.00758831]]
Updated weight i-->h
[[ 1.09795336  1.48286956 -0.4924492 ]
 [-0.3052542  -1.23037768  1.35057835]
 [ 

H = X . Wh

[[ 1.85760243  2.88907272 -0.50676686]
 [ 1.88406705  2.57010476  0.13080826]
 [-0.30078893 -1.57714394  2.00580666]]

H = X . Wh + bias_h
[[ 2.129468    2.40382432 -0.45129383]
 [ 2.15593262  2.08485636  0.18628129]
 [-0.02892336 -2.06239234  2.06127968]]

H_result: After applying activation function
[[0.89373449 0.91711846 0.38905319]
 [0.89622186 0.88942256 0.54643612]
 [0.49276966 0.11280618 0.88708242]]

Output = H_result . Wout
[[ 2.37113777]
 [ 2.04960393]
 [-0.75803841]]

Output = H_result . Wout + bias_out
[[ 1.97895658]
 [ 1.65742273]
 [-1.1502196 ]]

Calculated result: After applying activation function

[[0.87856989]
 [0.83989173]
 [0.24044897]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.12143011]
 [ 0.16010827]
 [-0.24044897]]
Derivative of sigmoid (output)
[[0.10668484]
 [0.13447361]
 [0.18263326]]
Delta output sum
[[ 0.01295475]
 [ 0.02153034]
 [-0.04391398]]
Updated weight h-->o
[[ 0.8059474 ]
 [ 2.48991371]
 [-1.62023073]]
Upd

 [-0.08280291 -2.10914779  2.05916669]]

H_result: After applying activation function
[[0.89350319 0.91932931 0.36986886]
 [0.89435894 0.89100124 0.52523558]
 [0.47931109 0.10821088 0.88687059]]

Output = H_result . Wout
[[ 2.46499463]
 [ 2.13374379]
 [-0.81009356]]

Output = H_result . Wout + bias_out
[[ 2.05009196]
 [ 1.71884112]
 [-1.22499623]]

Calculated result: After applying activation function

[[0.88595691]
 [0.8479795 ]
 [0.2270584 ]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.11404309]
 [ 0.1520205 ]
 [-0.2270584 ]]
Derivative of sigmoid (output)
[[0.10103726]
 [0.12891026]
 [0.17550288]]
Delta output sum
[[ 0.0115226]
 [ 0.019597 ]
 [-0.0398494]]
Updated weight h-->o
[[ 0.82836159]
 [ 2.55200969]
 [-1.67381825]]
Updated output bias
[[-0.41577566]]
Delta hidden sum
[[ 0.00090825  0.00218082 -0.00449508]
 [ 0.00153375  0.00485704 -0.00817957]
 [-0.0082383  -0.0098138   0.00669215]]
Updated weight i-->h
[[ 1.11097495  1.52148527 -0.56055661]
 [-0

H = X . Wh

[[ 1.88390268  2.96482277 -0.64316245]
 [ 1.87428491  2.61917181 -0.01357076]
 [-0.38121395 -1.65664742  2.03385508]]

H = X . Wh + bias_h
[[ 2.12457573  2.46462892 -0.61985537]
 [ 2.11495797  2.11897796  0.00973632]
 [-0.1405409  -2.15684127  2.05716217]]

H_result: After applying activation function
[[0.89326896 0.92162468 0.34981435]
 [0.89234854 0.8927341  0.50243406]
 [0.46492249 0.10369366 0.88666932]]

Output = H_result . Wout
[[ 2.56604556]
 [ 2.2256905 ]
 [-0.86658358]]

Output = H_result . Wout + bias_out
[[ 2.12688076]
 [ 1.7865257 ]
 [-1.30574838]]

Calculated result: After applying activation function

[[0.89348852]
 [0.85650079]
 [0.21319916]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.10651148]
 [ 0.14349921]
 [-0.21319916]]
Derivative of sigmoid (output)
[[0.09516678]
 [0.12290719]
 [0.16774528]]
Delta output sum
[[ 0.01013635]
 [ 0.01763708]
 [-0.03576315]]
Updated weight h-->o
[[ 0.85281053]
 [ 2.61723195]
 [-1.73184624]]
Upd

H = X . Wh + bias_h
[[ 2.12302899  2.48561875 -0.6782267 ]
 [ 2.10089021  2.13140211 -0.05153234]
 [-0.17940053 -2.18767339  2.05606068]]

H_result: After applying activation function
[[0.89312141 0.92312747 0.3366572 ]
 [0.89098967 0.89391804 0.48711976]
 [0.45526977 0.1008629  0.88655859]]

Output = H_result . Wout
[[ 2.63431062]
 [ 2.28857238]
 [-0.90504983]]

Output = H_result . Wout + bias_out
[[ 2.17886381]
 [ 1.83312558]
 [-1.36049664]]

Calculated result: After applying activation function

[[0.89833535]
 [0.86213365]
 [0.2041596 ]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.10166465]
 [ 0.13786635]
 [-0.2041596 ]]
Derivative of sigmoid (output)
[[0.09132895]
 [0.11885922]
 [0.16247846]]
Delta output sum
[[ 0.00928493]
 [ 0.01638669]
 [-0.03317154]]
Updated weight h-->o
[[ 0.86954225]
 [ 2.66044353]
 [-1.77126868]]
Updated output bias
[[-0.4561968]]
Delta hidden sum
[[ 0.00077067  0.00175293 -0.00367273]
 [ 0.00138396  0.00413413 -0.00725149]
 [-0


[[0.90449859]
 [0.86946554]
 [0.1925195 ]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.09550141]
 [ 0.13053446]
 [-0.1925195 ]]
Derivative of sigmoid (output)
[[0.08638089]
 [0.11349522]
 [0.15545574]]
Delta output sum
[[ 0.0082495 ]
 [ 0.01481504]
 [-0.02992826]]
Updated weight h-->o
[[ 0.89213626]
 [ 2.71706574]
 [-1.82408497]]
Updated output bias
[[-0.4776924]]
Delta hidden sum
[[ 0.00070357  0.00155363 -0.00327256]
 [ 0.00130238  0.00376672 -0.0067264 ]
 [-0.00658677 -0.00714465  0.00549485]]
Updated weight i-->h
[[ 1.12865985  1.5703857  -0.65067652]
 [-0.40837174 -1.35199722  1.43468135]
 [ 0.7774303   1.4548367  -0.1047154 ]
 [-0.03925835 -0.365425    0.62270293]]
Updated bias i-->h
[[ 0.21499124 -0.5109948  -0.0023897 ]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[ 1.90609015  3.0252224  -0.75539192]
 [ 1.8668318   2.6597974  -0.13268899]
 [-0.44763009 -1.71742222  2.05738428]]

H = X . Wh + bias_h
[[ 2.12108139  2.5142276  -0.7577816

 [-0.46957099 -1.73666432  2.06531243]]

H = X . Wh + bias_h
[[ 2.12007143  2.53049191 -0.80295113]
 [ 2.07105555  2.15891821 -0.18251582]
 [-0.26303865 -2.25096662  2.05466341]]

H_result: After applying activation function
[[0.89283876 0.92625196 0.3093946 ]
 [0.88805794 0.89649921 0.45449729]
 [0.43461689 0.09526612 0.88641798]]

Output = H_result . Wout
[[ 2.78189718]
 [ 2.42649605]
 [-0.98916496]]

Output = H_result . Wout + bias_out
[[ 2.29153469]
 [ 1.93613356]
 [-1.47952745]]

Calculated result: After applying activation function

[[0.90817351]
 [0.87392676]
 [0.18549881]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.09182649]
 [ 0.12607324]
 [-0.18549881]]
Derivative of sigmoid (output)
[[0.08339438]
 [0.11017878]
 [0.151089  ]]
Delta output sum
[[ 0.00765781]
 [ 0.0138906 ]
 [-0.02802683]]
Updated weight h-->o
[[ 0.90640575]
 [ 2.75185306]
 [-1.85717176]]
Updated output bias
[[-0.49101033]]
Delta hidden sum
[[ 0.00066411  0.00143949 -0.00303878]
 

[[0.91359004]
 [0.88062196]
 [0.17503979]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.08640996]
 [ 0.11937804]
 [-0.17503979]]
Derivative of sigmoid (output)
[[0.07894328]
 [0.10512692]
 [0.14440086]]
Delta output sum
[[ 0.00682149]
 [ 0.01254985]
 [-0.0252759 ]]
Updated weight h-->o
[[ 0.92868326]
 [ 2.80474064]
 [-1.90837419]]
Updated output bias
[[-0.51139331]]
Delta hidden sum
[[ 0.00060681  0.00127799 -0.0027026 ]
 [ 0.00117416  0.00322323 -0.00588836]
 [-0.00572761 -0.0059367   0.00485657]]
Updated weight i-->h
[[ 1.13866416  1.5962793  -0.69974621]
 [-0.44088639 -1.38644928  1.46203039]
 [ 0.78743461  1.48073031 -0.1537851 ]
 [-0.0652254  -0.38143599  0.61671853]]
Updated bias i-->h
[[ 0.1924809  -0.51955325 -0.02411035]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[ 1.92609877  3.07700961 -0.85353131]
 [ 1.86087337  2.69557362 -0.23681278]
 [-0.50611179 -1.76788526  2.07874892]]

H = X . Wh + bias_h
[[ 2.11857967  2.55745636 -0.8776416

 [-1.95574512]]
Updated output bias
[[-0.5300027]]
Delta hidden sum
[[ 0.0005577   0.00114372 -0.00241869]
 [ 0.00110405  0.00294257 -0.00542873]
 [-0.00527326 -0.00533878  0.00451328]]
Updated weight i-->h
[[ 1.14433472  1.61041041 -0.72680632]
 [-0.45899957 -1.40499616  1.47746292]
 [ 0.79310517  1.49486142 -0.18084521]
 [-0.07958498 -0.38983424  0.61351387]]
Updated bias i-->h
[[ 0.18003828 -0.52396902 -0.03573794]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[ 1.93743988  3.10527184 -0.90765153]
 [ 1.8578549   2.7154376  -0.29413766]
 [-0.53858455 -1.7948304   2.09097679]]

H = X . Wh + bias_h
[[ 2.11747817  2.58130282 -0.94338947]
 [ 2.03789319  2.19146858 -0.3298756 ]
 [-0.35854626 -2.31879942  2.05523885]]

H_result: After applying activation function
[[0.89259039 0.92964852 0.28021619]
 [0.88471856 0.89948077 0.41827089]
 [0.41131152 0.08957792 0.88647591]]

Output = H_result . Wout
[[ 2.95154847]
 [ 2.58801349]
 [-1.08762796]]

Output = H_result . Wout + bias_out
[

H = X . Wh

[[ 1.94804101  3.13099953 -0.95717359]
 [ 1.85528405  2.73371774 -0.34649691]
 [-0.56846239 -1.81901186  2.10250207]]

H = X . Wh + bias_h
[[ 2.11667399  2.60316044 -1.00331008]
 [ 2.02391702  2.20587865 -0.3926334 ]
 [-0.39982942 -2.34685095  2.05636557]]

H_result: After applying activation function
[[0.89251327 0.9310647  0.26829112]
 [0.88328543 0.90077618 0.40308352]
 [0.40135332 0.0873164  0.88658925]]

Output = H_result . Wout
[[ 3.0252871 ]
 [ 2.65906862]
 [-1.13104978]]

Output = H_result . Wout + bias_out
[[ 2.47823508]
 [ 2.11201659]
 [-1.6781018 ]]

Calculated result: After applying activation function

[[0.92260186]
 [0.89206565]
 [0.15734698]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.07739814]
 [ 0.10793435]
 [-0.15734698]]
Derivative of sigmoid (output)
[[0.07140767]
 [0.09628452]
 [0.13258891]]
Delta output sum
[[ 0.00552682]
 [ 0.01039241]
 [-0.02086247]]
Updated weight h-->o
[[ 0.96965406]
 [ 2.89781368]
 [-2.00097876]]
Upd

Updated weight i-->h
[[ 1.15431443  1.63436057 -0.77297945]
 [-0.49026264 -1.43604038  1.50444311]
 [ 0.80308488  1.51881157 -0.22701833]
 [-0.10417571 -0.4035545   0.6083154 ]]
Updated bias i-->h
[[ 0.15875493 -0.53106309 -0.05493086]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[ 1.95739932  3.15317214 -0.99999777]
 [ 1.85322361  2.74961764 -0.39168237]
 [-0.59443835 -1.83959488  2.11275852]]

H = X . Wh + bias_h
[[ 2.11615424  2.62210905 -1.05492864]
 [ 2.01197853  2.21855455 -0.44661323]
 [-0.43568342 -2.37065797  2.05782766]]

H_result: After applying activation function
[[0.8924634  0.932271   0.25827979]
 [0.88204902 0.90190339 0.3901663 ]
 [0.39277    0.08543771 0.88673617]]

Output = H_result . Wout
[[ 3.08955353]
 [ 2.72135936]
 [-1.16920845]]

Output = H_result . Wout + bias_out
[[ 2.52774024]
 [ 2.15954607]
 [-1.73102174]]

Calculated result: After applying activation function

[[0.92606378]
 [0.89655746]
 [0.15045693]]


::::::::::BACK PROPAGATION::::::::::::::



::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[ 1.96287411  3.165915   -1.02465355]
 [ 1.85211137  2.7588149  -0.41765282]
 [-0.60945623 -1.8513191   2.11879549]]

H = X . Wh + bias_h
[[ 2.11593559  2.63304471 -1.08456067]
 [ 2.00517284  2.22594461 -0.47755993]
 [-0.45639475 -2.38418939  2.05888837]]

H_result: After applying activation function
[[0.89244241 0.93295824 0.25264392]
 [0.88133912 0.90255527 0.38282848]
 [0.38784144 0.08438631 0.88684266]]

Output = H_result . Wout
[[ 3.12678116]
 [ 2.75758303]
 [-1.19144685]]

Output = H_result . Wout + bias_out
[[ 2.55646138]
 [ 2.18726324]
 [-1.76176664]]

Calculated result: After applying activation function

[[0.9280064 ]
 [0.8990999 ]
 [0.14656922]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.0719936 ]
 [ 0.1009001 ]
 [-0.14656922]]
Derivative of sigmoid (output)
[[0.06681052]
 [0.09071927]
 [0.12508668]]
Delta output sum
[[ 0.00480993]
 [ 0.00915358]
 [-0.01833386]]
Updated weight h-->o
[[ 0.9


Output = H_result . Wout
[[ 3.17891915]
 [ 2.80847299]
 [-1.22275705]]

Output = H_result . Wout + bias_out
[[ 2.59674334]
 [ 2.22629718]
 [-1.80493285]]

Calculated result: After applying activation function

[[0.93065169]
 [0.90258628]
 [0.14125165]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.06934831]
 [ 0.09741372]
 [-0.14125165]]
Derivative of sigmoid (output)
[[0.06453912]
 [0.08792429]
 [0.12129962]]
Delta output sum
[[ 0.00447568]
 [ 0.00856503]
 [-0.01713377]]
Updated weight h-->o
[[ 1.01140976]
 [ 2.98765047]
 [-2.09311817]]
Updated output bias
[[-0.58258511]]
Delta hidden sum
[[ 0.00043459  0.00082537 -0.00173264]
 [ 0.00091246  0.00223176 -0.00419156]
 [-0.0040869  -0.00389426  0.00359406]]
Updated weight i-->h
[[ 1.16105509  1.6499014  -0.8030681 ]
 [-0.51090678 -1.45593173  1.52250225]
 [ 0.80982553  1.53435241 -0.25710699]
 [-0.12026979 -0.41212836  0.60517079]]
Updated bias i-->h
[[ 0.14485144 -0.5354136  -0.06696038]]


::::::::::FORWARD

[[ 0.1392395  -0.53711104 -0.07169667]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[ 1.97643382  3.19677053 -1.08443541]
 [ 1.84965908  2.78125972 -0.48046745]
 [-0.64607006 -1.87939834  2.13386409]]

H = X . Wh + bias_h
[[ 2.11567332  2.65965949 -1.15613208]
 [ 1.98889858  2.24414868 -0.55216412]
 [-0.50683056 -2.41650937  2.06216742]]

H_result: After applying activation function
[[0.89241724 0.93460386 0.23937082]
 [0.87962656 0.90414462 0.36536246]
 [0.37593681 0.08192241 0.88717131]]

Output = H_result . Wout
[[ 3.21778714]
 [ 2.84652111]
 [-1.24622271]]

Output = H_result . Wout + bias_out
[[ 2.6268184 ]
 [ 2.25555237]
 [-1.83719145]]

Calculated result: After applying activation function

[[0.93256775]
 [0.9051284 ]
 [0.13738379]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.06743225]
 [ 0.0948716 ]
 [-0.13738379]]
Derivative of sigmoid (output)
[[0.06288514]
 [0.08587098]
 [0.11850949]]
Delta output sum
[[ 0.00424049]
 [ 0.00814672]
 [-

Updated weight i-->h
[[ 1.16800487  1.66541346 -0.8331378 ]
 [-0.53177425 -1.47559481  1.54095507]
 [ 0.81677532  1.54986447 -0.28717669]
 [-0.13641303 -0.42044011  0.60226456]]
Updated bias i-->h
[[ 0.13093375 -0.53956462 -0.07857727]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[ 1.98478019  3.21527793 -1.12031449]
 [ 1.84836717  2.79483782 -0.51804993]
 [-0.66818728 -1.89603492  2.14321962]]

H = X . Wh + bias_h
[[ 2.11571394  2.67571331 -1.19889175]
 [ 1.97930092  2.2552732  -0.59662719]
 [-0.53725353 -2.43559954  2.06464236]]

H_result: After applying activation function
[[0.89242114 0.93557824 0.23167243]
 [0.87860662 0.90510442 0.35511572]
 [0.36882671 0.08049803 0.88741881]]

Output = H_result . Wout
[[ 3.27294602]
 [ 2.90066308]
 [-1.27970427]]

Output = H_result . Wout + bias_out
[[ 2.66956886]
 [ 2.29728591]
 [-1.88308144]]

Calculated result: After applying activation function

[[0.93520691]
 [0.90865201]
 [0.13203533]]


::::::::::BACK PROPAGATION::::::::::::::

Updated bias i-->h
[[ 0.12688051 -0.5407374  -0.08187824]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[ 1.98891138  3.22430573 -1.13781369]
 [ 1.84778969  2.80149181 -0.53634536]
 [-0.67901477 -1.9040954   2.14787203]]

H = X . Wh + bias_h
[[ 2.11579189  2.68356833 -1.21969193]
 [ 1.9746702   2.26075442 -0.6182236 ]
 [-0.55213427 -2.44483279  2.06599378]]

H_result: After applying activation function
[[0.89242862 0.93605006 0.22799067]
 [0.87811185 0.90557416 0.35018557]
 [0.36536939 0.07981724 0.88755375]]

Output = H_result . Wout
[[ 3.3000049 ]
 [ 2.92728064]
 [-1.29620574]]

Output = H_result . Wout + bias_out
[[ 2.69057174]
 [ 2.31784748]
 [-1.90563891]]

Calculated result: After applying activation function

[[0.93646801]
 [0.91034441]
 [0.12947159]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.06353199]
 [ 0.08965559]
 [-0.12947159]]
Derivative of sigmoid (output)
[[0.05949568]
 [0.08161746]
 [0.1127087 ]]
Delta output sum
[[ 0.00377988]

Output = H_result . Wout
[[ 3.35012902]
 [ 2.97667748]
 [-1.32690472]]

Output = H_result . Wout + bias_out
[[ 2.72953387]
 [ 2.35608233]
 [-1.94749987]]

Calculated result: After applying activation function

[[0.93874704]
 [0.91341647]
 [0.12482623]]


::::::::::BACK PROPAGATION::::::::::::::


Error=target-calculated
[[ 0.06125296]
 [ 0.08658353]
 [-0.12482623]]
Derivative of sigmoid (output)
[[0.05750104]
 [0.07908682]
 [0.10924464]]
Delta output sum
[[ 0.00352211]
 [ 0.00684762]
 [-0.0136366 ]]
Updated weight h-->o
[[ 1.05979523]
 [ 3.08624132]
 [-2.19694438]]
Updated output bias
[[-0.62092184]]
Delta hidden sum
[[ 0.00035827  0.00064249 -0.00133359]
 [ 0.0007817   0.00179221 -0.0033817 ]
 [-0.00332576 -0.00304745  0.0029836 ]]
Updated weight i-->h
[[ 1.17404368  1.67848926 -0.85847597]
 [-0.54955424 -1.49202514  1.55683497]
 [ 0.82281413  1.56294027 -0.31251485]
 [-0.15006294 -0.42726225  0.60002461]]
Updated bias i-->h
[[ 0.11919257 -0.54291915 -0.08803553]]


::::::::::FORWARD 

Updated weight i-->h
[[ 1.17673038  1.68419068 -0.8695137 ]
 [-0.55735816 -1.49914871  1.56385046]
 [ 0.82550083  1.56864169 -0.32355258]
 [-0.15602234 -0.4301856   0.59911388]]
Updated bias i-->h
[[ 0.11407535 -0.5443413  -0.09205777]]


::::::::::FORWARD PROPAGATION:::::::::


H = X . Wh

[[ 2.00223121  3.25283237 -1.19306628]
 [ 1.84620887  2.82264677 -0.5939524 ]
 [-0.7133805  -1.92933431  2.16296433]]

H = X . Wh + bias_h
[[ 2.11630656  2.70849106 -1.28512405]
 [ 1.96028422  2.27830546 -0.68601017]
 [-0.59930515 -2.47367561  2.07090656]]

H_result: After applying activation function
[[0.89247802 0.93752583 0.21667926]
 [0.87656371 0.9070643  0.33492122]
 [0.35450268 0.07772435 0.88804313]]

Output = H_result . Wout
[[ 3.38615421]
 [ 3.01224586]
 [-1.34907273]]

Output = H_result . Wout + bias_out
[[ 2.75758319]
 [ 2.38367484]
 [-1.97764375]]

Calculated result: After applying activation function

[[0.94034019]
 [0.91557393]
 [0.12157024]]


::::::::::BACK PROPAGATION::::::::::::::